drop table person if exists
drop table patient if exists
drop table doctor if exists
drop table appointment if exists

CREATE TABLE person (id bigint generated by default as identity (start with 1), first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))
 
CREATE TABLE patient (id bigint NOT NULL, phone VARCHAR(255),PRIMARY KEY (id),CONSTRAINT FK_PERSON_PATIENT FOREIGN KEY (id) REFERENCES person (id))
 
CREATE TABLE doctor (id bigint NOT NULL, PRIMARY KEY (id), CONSTRAINT FK_PERSON_DOCTOR FOREIGN KEY (id) REFERENCES person (id))

CREATE TABLE appointment (id bigint NOT NULL, visit_date bigint NOT NULL, patient_id bigint NOT NULL, doctor_id bigint NOT NULL, PRIMARY KEY (id), CONSTRAINT FK_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id), CONSTRAINT FK_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor (id))


insert into person (first_name, last_name) values ('George', 'Clinton')
insert into person (first_name, last_name) values ('Herbie', 'Hancock')
insert into person (first_name, last_name) values ('Jef Lee', 'Johnson')

insert into doctor (id) values (1)
insert into doctor (id) values (2)
insert into doctor (id) values (3)
